[Icon Theme]
Name=tulasi.Noir
Comment=Wherever I go, the desktop follows. Deeper blacks, sharper contours, pure focus. Handcrafted 32x32 pixel art in shadows by Shringar Studio.
Inherits=breeze,breeze-dark,Adwaita,hicolor
FollowsColorScheme=true
Directories=scalable/apps,scalable/actions,scalable/places,scalable/status,scalable/devices,scalable/emblems,scalable/mimetypes,scalable/categories,scalable/symbolic

[scalable/apps]
Size=32
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[scalable/actions]
Size=22
MinSize=16
MaxSize=512
Type=Scalable
Context=Actions

[scalable/places]
Size=22
MinSize=22
MaxSize=1024
Type=Scalable
Context=Places

[scalable/status]
Size=22
MinSize=16
MaxSize=512
Type=Scalable
Context=Status

[scalable/devices]
Size=22
MinSize=16
MaxSize=512
Type=Scalable
Context=Devices

[scalable/emblems]
Size=8
MinSize=8
MaxSize=64
Type=Scalable
Context=Emblems

[scalable/mimetypes]
Size=22
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes

[scalable/categories]
Size=22
MinSize=16
MaxSize=512
Type=Scalable
Context=Categories

[scalable/symbolic]
Size=16
MinSize=16
MaxSize=31
Type=Scalable
Context=Actions
